### PR TITLE
preparation for implementation of schema document tables

### PR DESCRIPTION
**Pull request by AIS-RyoMukai**
Update buildings and land use pages.

Changes made:
Change class diagram images to those from EA output.
Implementation of klass table
Deletion of old tables

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by AAS-YknKawakita** [comment]
hello @ReesePlews  (cc:@AIS-RyoMukai) 
I was checked output PDF&html files.
I don't think there is any error.
Please merge if there are no problems.

Thank you for your support.

**Comment by ReesePlews** [comment]
hello @AAS-YknKawakita and @AIS-RyoMukai, in looking at the SVG images, i am wondering if they are not visible because the color of the text of the attributes is not black but some brown-ish color? 

instead of removing the call to the .svg image lets just comment that out "//" but keep it in the file. if you can check the color of the text in EA when the SVG is output, then perhaps it is possible to got back to SVG because it is not a metanorma issue but an EA/color issue.  brown text with pink background may be the issue.

please update the commit and i will merge when it is finished. thank you.

**Comment by AAS-YknKawakita** [comment]
hello @ReesePlews 
Thank you for checking.
I've reinstated the SVG images with the comment out.
Please check it out. thank you.

**Comment by ReesePlews** [comment]
hello @AAS-YknKawakita thank you for making the updates. on the next PRs i think we should label them someway so we know sub-clause we are working on.  you added "Update buildings and land use pages." but perhaps the clause numbers are helpful to have in the title of the PR.  the idea is to be able to find which PR goes with which sub-clause quickly, if needed.  please consider that. thank you.

**Pull request merged**
