### PR TITLE
Urgent fix for Document 001 v4

### LINKED ISSUE #145: (URGENT) render of gml_dict failure
Clauses after 4.7 are not rendered after merge of #129 

image

### PR DESCRIPTION
**Pull request by ronaldtse**
This is clean up necessary after #129 .

Fixes #145

### CODE REVIEW

**Comment by ronaldtse** [comment]
Document compilation errors:

FYI @opoudjis :
```
Style: (ID _dmelement_dislocationtype_xml): More than 1 ordered list in a numbered clause
undefined method `previous=' for nil
gems/isodoc-2.11.1/lib/isodoc/html_function/postprocess_footnotes.rb:30:in `footnote_backlinks1'
gems/isodoc-2.11.1/lib/isodoc/html_function/postprocess_footnotes.rb:41:in `block in footnote_backlinks'
gems/nokogiri-1.16.7-arm64-darwin/lib/nokogiri/xml/node_set.rb:235:in `block in each'
gems/nokogiri-1.16.7-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `upto'
gems/nokogiri-1.16.7-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `each'
gems/isodoc-2.11.1/lib/isodoc/html_function/postprocess_footnotes.rb:38:in `each_with_index'
gems/isodoc-2.11.1/lib/isodoc/html_function/postprocess_footnotes.rb:38:in `footnote_backlinks'
gems/isodoc-2.11.1/lib/isodoc/html_function/postprocess.rb:29:in `html_cleanup'
gems/isodoc-2.11.1/lib/isodoc/html_function/postprocess.rb:16:in `toHTML'
gems/isodoc-2.11.1/lib/isodoc/html_function/postprocess.rb:11:in `postprocess'
gems/isodoc-2.11.1/lib/isodoc/convert.rb:171:in `convert'
gems/isodoc-2.11.1/lib/isodoc/html_convert.rb:26:in `convert'
gems/metanorma-plateau-0.1.3/lib/metanorma/plateau/processor.rb:41:in `output'
gems/metanorma-2.0.3/lib/metanorma/compile/compile.rb:175:in `process_output_threaded'
gems/metanorma-2.0.3/lib/metanorma/compile/compile.rb:167:in `block in process_exts1'
gems/metanorma-2.0.3/lib/metanorma/util/worker_pool.rb:21:in `block (3 levels) in init_thread'
<internal:kernel>:187:in `loop'
gems/metanorma-2.0.3/lib/metanorma/util/worker_pool.rb:19:in `block (2 levels) in init_thread'
gems/metanorma-2.0.3/lib/metanorma/util/worker_pool.rb:18:in `catch'
gems/metanorma-2.0.3/lib/metanorma/util/worker_pool.rb:18:in `block in init_thread'
```

**Review by ReesePlews — COMMENTED** [review]
hi @ronaldtse thanks for flagging these. i looked at the xml file ( DataQualityAttribute_lod1HeightType.xml ) but i am not seeing the "（使用不可）" characters in the original xml file, or in the table after doing a generate. i could only check the HTML and this table seems to be in the area that properly compiles. here is an image.

image

i wonder if they were something that happened during the initial conversion?

let me wait awhile until the other errors are corrected and i will come back to this.

**Comment by ronaldtse** [comment]
@ReesePlews the document currently does not compile yet, so this must be an older version.

**Comment by opoudjis** [comment]
Done, you will need to pull isodoc.

**Comment by ReesePlews** [comment]
i noticed in the build that one of the xml codelist files is misspelled in the code... 

`FirePreventionDIstrict_usage.xml`

is on disk actually named

`FirePreventionDistrict_usage.xml`

**Comment by ronaldtse** [comment]
The remaining issues are for the PLATEAU team to resolve, they are:
* #150 
* #151 
* #152 
* #153 

Merging this now.

**Comment by ReesePlews** [comment]
i think #149 also needs to be in the list of issues the Plateau team should check

**Comment by ronaldtse** [comment]
@ReesePlews yes, updated list.

**Pull request merged**
