### PR TITLE
align text between doc01 and doc02 - updates to 20240802 pptx slides 1 - 20

### PR DESCRIPTION
**Pull request by ReesePlews**
some slides could not be processed; those slides will need to be checked by the Plateau Team.

@Intelligent2013 when you have time, could you check my revisions. these are primarily edits to tables and i am not so confident about editing tables. 

the purpose of these revisions is to align text between both doc01 and doc02. 

later, after the text has been aligned and checked we want to see if it is possible to have a set of unique single files for each common text "block" and use the "include" function in both documents to read in that single file. 

thank you

### CODE REVIEW

**Comment by Intelligent2013** [comment]
> these are primarily edits to tables and i am not so confident about editing tables.

@ReesePlews thank you for the updates. Did you try to generate the PDF after editing? If you are satisfied with the result, then fill free to merge the PR. Or do you not have the merge permissions? I just don't have the pptx slides, so I can't to confirm the correctness of the changes.

**Comment by ReesePlews** [comment]
sorry, @Intelligent2013 i forgot the answer about the PDF. i have not tried to generate these changes locally, should i do that?  the github action to run the generate has been failing the past few days. @ronaldtse and other dev members are checking that. 

if you would like me to generate locally let me know. that would be on the revised code before the "push" command or after "push" and before "a pull request"?  i will check back in the morning. thank you.

**Comment by Intelligent2013** [comment]
> if you would like me to generate locally let me know. that would be on the revised code before the "push" command or after "push" and before "a pull request"? i will check back in the morning. thank you.

@ReesePlews the current docker image contains the `relaton-plateau` version `1.19.2`, but the error
```
/usr/local/bundle/gems/relaton-plateau-1.19.2/lib/relaton/plateau/bibitem.rb:47:in `block (2 levels) in to_xml': undefined method `to_xml' for nil:NilClass (NoMethodError)

              cover.to_xml b
                   ^^^^^^^
Did you mean?  to_yaml
```
fixed in the version `1.19.3` (https://github.com/relaton/relaton-plateau/issues/14). The latest version is `1.19.5`.
The next version of docker image will contain the latest `relaton-plateau`.

So, to make sure that the changes correspond to the pptx slides, please, generate the PDFs locally:
```
bundle update
bundle exec metanorma site generate
```

> that would be on the revised code before the "push" command or after "push" and before "a pull request"?

All the same. `.gitignore` contains `/_site`, so the generated files don't upload in any case.

**Comment by Intelligent2013** [comment]
@ReesePlews the PDF generated now ([artifacts](https://github.com/metanorma/mn-samples-plateau/actions/runs/10678066342?pr=169)). If the rendered modified tables match to the slides, then feel free to merge PR.

**Comment by ReesePlews** [comment]
thank you @Intelligent2013, i will check these and get back to you. glad the build is working again.

**Comment by ronaldtse** [comment]
@ReesePlews is there a reason this PR is not merged? Thanks.

**Comment by ReesePlews** [comment]
yes @ronaldtse and @Intelligent2013 , lets merge this one into main. thank you.

i am still working on 0828a a different branch, no commits or PR yet on that.

**Pull request merged**
