### PR TITLE
Add collection and build

### PR DESCRIPTION
**Pull request by ronaldtse**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by ronaldtse** [comment]
Works, merging.

Screenshot 2024-10-09 at 9 03 03 AM

**Comment by ReesePlews** [comment]
hi @ronaldtse when you are ready, please let us know what this updates are for. thanks for continuing to check the document.

**Comment by ronaldtse** [comment]
@ReesePlews this is for @strogonoff to test out Firelight using a collection of the 001 and 002 documents. You can download the build artifact from the "collection" action to see the HTML pages split (for now, before Firelight is active).

**Comment by ReesePlews** [comment]
thanks @ronaldtse i will talk with Anton later this week for an update on the html work. i will download that artifact. thanks!

**Pull request merged**
