### PR TITLE
271 aas reflection of ver50 part1

### PR DESCRIPTION
**Pull request by AIS-NagayaYumi**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by ReesePlews** [comment]
hello @AIS-RyoMukai @AIS-NagayaYumi are you ready for this to be merged?

**Comment by AIS-RyoMukai** [comment]
@ReesePlews  @AIS-NagayaYumi 
確認中です、もう少しお待ちください
Confirming, please wait a little longer

**Comment by AIS-RyoMukai** [comment]
@ReesePlews  @AIS-NagayaYumi  @AAS-YknKawakita 
We were able to confirm, please merge.
確認できました、マージお願いします。

**Comment by ReesePlews** [comment]
thank you @AIS-RyoMukai running the merge now...

**Pull request merged**
