### PR TITLE
Minor text corrections and updating to latest XMI files

### PR DESCRIPTION
**Pull request by AIS-RyoMukai**
Correction of XMI content and correction of  Adoc errors found as a by-product
We will send you another merge request after confirmation.

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by ReesePlews** [comment]
hello @AIS-RyoMukai let me know when this is ready to be merged. thank you.

**Comment by AIS-RyoMukai** [comment]
@ReesePlews  @AAS-YknKawakita 
確認中です、またご連絡します。
We are checking and will contact you again.

**Comment by ReesePlews** [comment]
hello @AIS-RyoMukai if this commit covers #173 please indicate so i can mark those off. thank you.

**Comment by AAS-YknKawakita** [comment]
hello @ReesePlews
We are pleased to report that the fixes in #137 have also been addressed in this amendment.
We have also just finished the build with the remote docker, so we will check it together and let you know again if there are no problems.

**Comment by ReesePlews** [comment]
thank you @AAS-YknKawakita after you request the merge i will close that issue.

**Comment by AAS-YknKawakita** [comment]
hello @ReesePlews (cc:@AIS-RyoMukai)
I was checked output PDF&html files.
I don't think there is any error.
We have also fixed the #173 issue and confirmed that it has been changed.

Please merge If there are no problems with this content.
Thank you for your support.

**Pull request merged**
