### PR TITLE
Update section-02.adoc common text slide 01

### PR DESCRIPTION
**Pull request by ReesePlews**
document alignment; minor change; slide 01
hello Alexander, would you please check this update and merge to main if it is correct. thank you;

### CODE REVIEW

**Comment by Intelligent2013** [comment]
> document alignment; minor change; slide 01

@ReesePlews could you share the document with slides? Thanks.

**Comment by ReesePlews** [comment]
thank you @Intelligent2013 for checking the code. the slides are not yet translated, i am just doing them one by one. i was only going to do a couple as a test.  i will post slide 1 in a comment below.

after the code in both documents are "aligned" the client would like to remove the code and place a single copy into a "common" folder (under sources/common) and then using an include statement, load that code into each document. the idea here is to "edit/maintain" only each single file in the common location.

**Review by Intelligent2013 — APPROVED** [review]

**Comment by Intelligent2013** [comment]
@ReesePlews thanks.

**Comment by ReesePlews** [comment]
@Intelligent2013 if the PR is verified ok, please merge to main. thank you.

**Pull request merged**
